---
title: "**STAT 679 Final Project Proposal**"
author:
   - Xiaoyang Wang
   - Ziang Zeng
geometry: "left=1.5cm,right=1.5cm,top=1.5cm,bottom=1.5cm"
classoption: twocolumn
output:
  pdf_document:
    number_sections: yes
header-includes: 
  - \usepackage{booktabs}
  - \usepackage{bm}
  - \usepackage{extarrows}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F, echo = F,
                      fig.height = 4)
```

# Astronomical Challange 
Our research focuses on classifying celestial objects into stars, galaxies or quasars using their spectral characteristics. With the advancement of astronomical technology, we can obtain a large amount of data, including images and spectral information, from telescopes and large-scale photometry.

The central question of our research is: "How can we effectively use image and spectral data to accurately classify different types of stellar objects?"

# Data

# Methods

# Contribution
Our workload is distributed equally in this project. We are going to preprocess the data together by merging and visualizing. As mentioned before, each of us will be responsible to complete one of the separate models with proper tuning and validation. After training the separate models, we will merge the models by combining their results through weighted average or regression to produce a final model with better accuracy expected.

